import { AnalysisResults, AnalysisInput } from "@/types/analysis";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";

export const exportToPDF = (input: AnalysisInput, results: AnalysisResults) => {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text(`AI Executive Report: ${input.companyName}`, 14, 22);
  
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(`Industry: ${input.industry} | Generated by Bizleap AI`, 14, 30);
  
  // Executive Summary
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text("Executive Summary", 14, 45);
  doc.setFontSize(12);
  const splitSummary = doc.splitTextToSize(results.executiveSummary.marketPosition, 180);
  doc.text(splitSummary, 14, 55);
  
  // Health Scores
  doc.setFontSize(16);
  doc.text("Health Scores", 14, 80);
  const scoresData = [
    ["Overall", `${results.healthScores.overall}/100`],
    ["Competitive", `${results.healthScores.competitive}/100`],
    ["Innovation", `${results.healthScores.innovation}/100`],
    ["SEO & Brand", `${results.healthScores.seo}/100`],
  ];
  
  autoTable(doc, {
    startY: 85,
    head: [["Metric", "Score"]],
    body: scoresData,
    theme: 'striped',
    headStyles: { fillColor: [99, 102, 241] } // brand-500
  });
  
  // Recommendations
  const finalY = (doc as any).lastAutoTable.finalY || 130;
  doc.setFontSize(16);
  doc.text("Top Product Recommendations", 14, finalY + 15);
  
  const recsData = results.dynamicRecommendations.product.map(r => [
    r.title,
    r.priorityLevel,
    r.expectedImpact,
    r.estimatedROI
  ]);
  
  autoTable(doc, {
    startY: finalY + 20,
    head: [["Recommendation", "Priority", "Impact", "Est. ROI"]],
    body: recsData,
    theme: 'grid',
    headStyles: { fillColor: [99, 102, 241] }
  });
  // Market Share
  const finalY2 = (doc as any).lastAutoTable.finalY || 130;
  doc.setFontSize(16);
  doc.text("Market Share Analysis", 14, finalY2 + 15);
  doc.setFontSize(12);
  doc.text(results.marketShare.explanation, 14, finalY2 + 25);
  
  const shareData = [
    [input.companyName, `${results.marketShare.myCompany.share}%`],
    ...results.marketShare.competitors.map(c => [c.name, `${c.share}%`]),
    ["Others", `${results.marketShare.others}%`]
  ];
  
  autoTable(doc, {
    startY: finalY2 + 35,
    head: [["Company", "Estimated Share"]],
    body: shareData,
    theme: 'striped',
    headStyles: { fillColor: [99, 102, 241] }
  });

  // SWOT Analysis
  const finalY3 = (doc as any).lastAutoTable.finalY || 200;
  if (finalY3 > 250) doc.addPage();
  const swotStartY = finalY3 > 250 ? 20 : finalY3 + 15;
  
  doc.setFontSize(16);
  doc.text("AI SWOT Analysis", 14, swotStartY);
  
  autoTable(doc, {
    startY: swotStartY + 10,
    head: [["Type", "Insight", "Priority", "Impact"]],
    body: [
      ...results.swot.strengths.map(s => ["Strength", s.text, s.priority, s.impactScore]),
      ...results.swot.weaknesses.map(w => ["Weakness", w.text, w.priority, w.impactScore]),
      ...results.swot.opportunities.map(o => ["Opportunity", o.text, o.priority, o.impactScore]),
      ...results.swot.threats.map(t => ["Threat", t.text, t.priority, t.impactScore]),
    ],
    theme: 'grid',
    headStyles: { fillColor: [99, 102, 241] }
  });
  
  doc.save(`${input.companyName}-AI-Report.pdf`);
};

export const exportToExcel = (input: AnalysisInput, results: AnalysisResults) => {
  const wb = XLSX.utils.book_new();
  
  // Features Sheet
  const featuresWs = XLSX.utils.json_to_sheet(results.comparisonData.features);
  XLSX.utils.book_append_sheet(wb, featuresWs, "Features Comparison");
  
  // Pricing Sheet
  const pricingWs = XLSX.utils.json_to_sheet(results.comparisonData.pricing);
  XLSX.utils.book_append_sheet(wb, pricingWs, "Pricing Comparison");
  
  // Metrics Sheet
  const metricsWs = XLSX.utils.json_to_sheet(results.comparisonData.radarMetrics);
  XLSX.utils.book_append_sheet(wb, metricsWs, "Metrics");
  
  XLSX.writeFile(wb, `${input.companyName}-Competitive-Data.xlsx`);
};
