"use client";

import { useAppStore } from "@/store/useAppStore";
import { AnimatedCard } from "@/components/ui/AnimatedCard";
import { RecommendationAccordion } from "@/components/ui/RecommendationAccordion";
import { Lightbulb, Megaphone, Search, DollarSign, Users, HeartHandshake, TrendingUp } from "lucide-react";
import { useState } from "react";
import { cn } from "@/lib/utils";

export default function RecommendationsPage() {
  const { analysisResults } = useAppStore();
  const [activeCategory, setActiveCategory] = useState<string>("product");

  if (!analysisResults) {
    return <div>No analysis found.</div>;
  }

  const { dynamicRecommendations } = analysisResults;

  const categories = [
    { id: "product", label: "Product & Innovation", icon: Lightbulb, data: dynamicRecommendations.product },
    { id: "marketing", label: "Marketing Growth", icon: Megaphone, data: dynamicRecommendations.marketing },
    { id: "seo", label: "SEO & Content", icon: Search, data: dynamicRecommendations.seo },
    { id: "sales", label: "Sales Optimization", icon: DollarSign, data: dynamicRecommendations.sales },
    { id: "customerExperience", label: "Customer Experience", icon: HeartHandshake, data: dynamicRecommendations.customerExperience },
    { id: "revenue", label: "Revenue & Pricing", icon: TrendingUp, data: dynamicRecommendations.revenue },
  ];

  const activeData = categories.find(c => c.id === activeCategory)?.data || [];

  return (
    <div className="space-y-8 pb-12">
      <div>
        <h1 className="text-3xl font-bold tracking-tight mb-2 flex items-center gap-2">
          <Lightbulb className="w-8 h-8 text-brand-500" /> AI Recommendation Engine
        </h1>
        <p className="text-muted-foreground max-w-2xl">
          Actionable, step-by-step strategic recommendations generated by our AI consultant based on market gaps and competitive analysis.
        </p>
      </div>

      <div className="flex flex-wrap gap-2 mb-8">
        {categories.map((cat) => (
          <button
            key={cat.id}
            onClick={() => setActiveCategory(cat.id)}
            className={cn(
              "px-4 py-2 rounded-full text-sm font-medium transition-colors flex items-center gap-2",
              activeCategory === cat.id 
                ? "bg-brand-600 text-white shadow-lg shadow-brand-500/20" 
                : "bg-white/5 text-muted-foreground hover:bg-white/10 hover:text-foreground"
            )}
          >
            <cat.icon className="w-4 h-4" />
            {cat.label}
          </button>
        ))}
      </div>

      <AnimatedCard delay={0.1} className="bg-transparent border-none shadow-none p-0">
        {activeData.length === 0 ? (
          <div className="text-center py-12 text-muted-foreground bg-black/20 rounded-xl border border-white/5">
            No recommendations generated for this category.
          </div>
        ) : (
          <div className="space-y-4">
            {activeData.map((rec, idx) => (
              <RecommendationAccordion key={idx} recommendation={rec} index={idx} />
            ))}
          </div>
        )}
      </AnimatedCard>

    </div>
  );
}
